// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbhnszwehbdpefyghbqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaG5zendlaGJkcGVmeWdoYnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjY2NzcsImV4cCI6MjA1OTk0MjY3N30.lm58IIVM_-kQ8fVpcA8AP1hRrXOroQKudYGsFdFpoz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);