// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgordyvlpqvtbetijrbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnb3JkeXZscHF2dGJldGlqcmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MzM5ODksImV4cCI6MjA3NzQwOTk4OX0.-z6-Fz2BPryK7lwpRymz734BWVc6SVonm0vVSgNg-0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);